name: mercenaryhub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  cloud_firestore: ^5.6.7
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  geolocator: ^14.0.0
  image_picker: ^1.1.2
  http: ^1.4.0
  kakao_flutter_sdk_user: ^1.9.5 # 카카오 로그인 API 패키지
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  fake_cloud_firestore: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 800
