name: 🔧 Setting (setting)
description: 프로젝트에 필요한 셋팅 파일 구성
title: "제목"
labels: ["setting"]
body:
  - type: markdown
    attributes:
      value: "🚀 **개요**"
  - type: textarea
    id: summary
    attributes:
      label: 어떤 기능을 추가하나요?
      placeholder: 예) HomeView View 구성
    validations:
      required: true

  - type: markdown
    attributes:
      value: "🔍 **작업 상세 내용**"
  - type: textarea
    id: details
    attributes:
      label: 작업에 포함될 세부 항목
      placeholder: |
        - 어떤 파일을 수정할지
        - 어느 위젯인지 등
    validations:
      required: false
