// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7STlPY1Y5zscK3iShyifV7UEPtn0_3FQ',
    appId: '1:432460783376:web:f195e9ebad0d346d874f95',
    messagingSenderId: '432460783376',
    projectId: 'forwin-da312',
    authDomain: 'forwin-da312.firebaseapp.com',
    storageBucket: 'forwin-da312.firebasestorage.app',
    measurementId: 'G-Y91V0XEQK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqxGTXJkq8iHUTj3cEqn1BxmqiBlp348',
    appId: '1:432460783376:android:eb88f3de3e6aea2f874f95',
    messagingSenderId: '432460783376',
    projectId: 'forwin-da312',
    storageBucket: 'forwin-da312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9kkH0rD5saqgR5CwqupZMBDXhedYXCcE',
    appId: '1:432460783376:ios:e720d3bc346d5abf874f95',
    messagingSenderId: '432460783376',
    projectId: 'forwin-da312',
    storageBucket: 'forwin-da312.firebasestorage.app',
    iosBundleId: 'com.example.mercenaryhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9kkH0rD5saqgR5CwqupZMBDXhedYXCcE',
    appId: '1:432460783376:ios:e720d3bc346d5abf874f95',
    messagingSenderId: '432460783376',
    projectId: 'forwin-da312',
    storageBucket: 'forwin-da312.firebasestorage.app',
    iosBundleId: 'com.example.mercenaryhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7STlPY1Y5zscK3iShyifV7UEPtn0_3FQ',
    appId: '1:432460783376:web:76d8f7b5a043c6b0874f95',
    messagingSenderId: '432460783376',
    projectId: 'forwin-da312',
    authDomain: 'forwin-da312.firebaseapp.com',
    storageBucket: 'forwin-da312.firebasestorage.app',
    measurementId: 'G-K1FWYQEE61',
  );
}
